name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/bkerler/oppo_ozip_decrypt ./
           
    - name: Build
      run: |
        sudo apt install python3-pip wget
        wget https://bootstrap.pypa.io/ez_setup.py
        sudo python3 ez_setup.py
        pip3 install pycryptodome
        pip3 install docopt
        wget https://assorted.downloads.oppo.com/firmware/CPH1831/CPH1831EX_11_OTA_0220_all_j23ELrwgufrf.ozip &> /dev/null
        ./ozipdecrypt.py *.ozip
        7z l -ba *.zip
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./out/boot.img

