name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/bkerler/oppo_ozip_decrypt ./
           
    - name: Build
      run: |
        sudo apt install python3-pip wget
        wget https://bootstrap.pypa.io/ez_setup.py
        sudo python3 ez_setup.py
        pip3 install pycryptodome
        pip3 install docopt
        wget https://download.c.realme.com/osupdate/RMX1801EX_11_OTA_2120_all_4q5L63MjpxAp.ozip
        ./ozipdecrypt.py *.ozip
        unzip RMX1801EX_11_OTA_2120_all_4q5L63MjpxAp.zip -d ./

    - name: Upload GSI to BitSend
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./boot.img
