name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/bkerler/oppo_ozip_decrypt ./
           
    - name: Build
      run: |
        sudo apt install python3-pip wget
        wget https://bootstrap.pypa.io/ez_setup.py
        sudo python3 ez_setup.py
        pip3 install pycryptodome
        pip3 install docopt
        wget https://assorted.downloads.oppo.com/firmware/CPH1831_P/CPH1831EX_11_OTA_1320_all_VBccG7HONJs6.ozip
        ./ozipdecrypt.py *.ozip
        unzip CPH1831EX_11_OTA_1320_all_VBccG7HONJs6.zip -d ./

    - name: Upload GSI to BitSend
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./boot.img
