name: Build App
on: 
   workflow_dispatch:
     branches: [ master ]
   watch:
     types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/bkerler/oppo_ozip_decrypt ./
           
    - name: Build
      run: |
        sudo apt install python3-pip wget
        pip3 install -r requirements.txt
        
        ./ozipdecrypt.py *.ozip
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: ./out/boot.img
